services:
  # PHP Apache 服務
  web:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: wati_automation_web
    ports:
      - "9090:80"  # 使用 9090 端口，避免與 pet_charity 衝突
    volumes:
      # 掛載專案文件
      - .:/var/www/html
      # 掛載數據目錄以保持數據持久化
      - ./data:/var/www/html/data
    environment:
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_DISPLAY_ERRORS=1
      - PHP_DISPLAY_STARTUP_ERRORS=1
    depends_on:
      - mysql
    networks:
      - wati_network
    restart: unless-stopped

  # MySQL 資料庫服務
  mysql:
    image: mysql:8.0
    container_name: wati_automation_mysql
    ports:
      - "3308:3306"  # 使用 3308 端口，避免與 pet_charity_mysql 衝突
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wati_automation
      MYSQL_USER: wati_user
      MYSQL_PASSWORD: wati_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - wati_network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin（資料庫管理）
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wati_automation_phpmyadmin
    ports:
      - "9091:80"  # 使用 9091 端口，避免與 pet_charity_phpmyadmin 衝突
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - mysql
    networks:
      - wati_network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  wati_network:
    driver: bridge 