version: '3.8'

services:
  # PHP Apache 服務（生產環境）
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: wati_automation_web_prod
    ports:
      - "80:80"
    volumes:
      # 只掛載數據目錄，不掛載源碼
      - ./data:/var/www/html/data
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_MEMORY_CONSUMPTION=128
    depends_on:
      - mysql
    networks:
      - wati_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # MySQL 資料庫服務（生產環境）
  mysql:
    image: mysql:8.0
    container_name: wati_automation_mysql_prod
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wati_automation
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - wati_network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Redis 快取服務（生產環境）
  redis:
    image: redis:7-alpine
    container_name: wati_automation_redis_prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data_prod:/data
    networks:
      - wati_network
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Nginx 反向代理（生產環境）
  nginx:
    image: nginx:alpine
    container_name: wati_automation_nginx_prod
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - wati_network
    restart: unless-stopped

volumes:
  mysql_data_prod:
    driver: local
  redis_data_prod:
    driver: local

networks:
  wati_network:
    driver: bridge 